import { type WorldProject } from '@world-forge/shared';
import type { DeepTimeProject } from './deepTimePipeline';
export type PreAgingTerrainState = {
    elevation: Float32Array;
    water: Uint8Array;
};
export type TerrainStateSummary = {
    meanElevation: number;
    elevationStdDev: number;
    meanLocalRelief: number;
    p95LocalRelief: number;
    ruggedTerrainShare: number;
    flatTerrainShare: number;
    boundaryMeanRelief: number;
    interiorMeanRelief: number;
    boundaryReliefRatio: number;
    basinFloorShare: number;
    coastlineCellShare: number;
    landCellShare: number;
    landmassCount: number;
    largestLandmassShare: number;
    cratonMeanRelief: number;
    nonCratonMeanRelief: number;
    cratonCellCount: number;
    nonCratonCellCount: number;
};
export type ProcessPressureSummary = {
    cratonTectonicGainPressure: number;
    nonCratonTectonicGainPressure: number;
    tectonicComparisonAvailable: boolean;
    cratonTectonicOpportunity: number;
    nonCratonTectonicOpportunity: number;
    cratonWeatheringLossPressure: number;
    nonCratonWeatheringLossPressure: number;
    weatheringComparisonAvailable: boolean;
    cratonWeatheringReliefOpportunity: number;
    nonCratonWeatheringReliefOpportunity: number;
    cratonGlacialLossPressure: number;
    nonCratonGlacialLossPressure: number;
    glacialComparisonAvailable: boolean;
    cratonGlacialEligibleCells: number;
    nonCratonGlacialEligibleCells: number;
    cratonCoastalLossPressure: number;
    nonCratonCoastalLossPressure: number;
    coastalComparisonAvailable: boolean;
    cratonCoastalOpportunity: number;
    nonCratonCoastalOpportunity: number;
};
export type DeepTimeTerrainChangeDiagnostics = {
    before: TerrainStateSummary;
    after: TerrainStateSummary;
    meanElevationDelta: number;
    elevationStdDevDelta: number;
    meanLocalReliefDelta: number;
    p95LocalReliefDelta: number;
    ruggedTerrainShareDelta: number;
    flatTerrainShareDelta: number;
    boundaryMeanReliefDelta: number;
    interiorMeanReliefDelta: number;
    boundaryReliefRatioDelta: number;
    basinFloorShareDelta: number;
    coastlineCellShareDelta: number;
    landCellShareDelta: number;
    landmassCountDelta: number;
    largestLandmassShareDelta: number;
    cratonMeanReliefDelta: number;
    nonCratonMeanReliefDelta: number;
    cratonComparisonAvailable: boolean;
    cratonRelativeReliefRetention: number;
    uniqueElevationChangedCells: number;
    uniqueWaterChangedCells: number;
    processPressure: ProcessPressureSummary;
    tectonicAdjustmentOperations: number;
    impactAdjustmentOperations: number;
    weatheringOperations: number;
    glacialErosionOperations: number;
    coastalAdjustmentOperations: number;
    floodedValleyOperations: number;
};
export declare function capturePreAgingTerrain(project: WorldProject): PreAgingTerrainState;
export declare function attachDeepTimeTerrainChangeDiagnostics(project: DeepTimeProject, beforeState: PreAgingTerrainState): DeepTimeTerrainChangeDiagnostics;
//# sourceMappingURL=deepTimeTerrainDiagnostics.d.ts.map