import { type GenerationConfig, type ParameterRanges, type WorldProject } from '@world-forge/shared';
export type PresetTestMode = 'short' | 'full' | 'deep';
export type PresetTestStatus = 'pass' | 'warning' | 'fail' | 'error';
export type TestStarPreset = 'sol-like' | 'habitable';
export type PresetTestCase = {
    id: string;
    seed: string;
    starPresetId: TestStarPreset;
    worldPresetId: string;
    baselineId: string;
};
export type WorldFingerprint = {
    starClass: string;
    stellarMass: number;
    stellarLuminosity: number;
    stellarTemperatureK: number;
    orbitalPeriodDays: number;
    rotationPeriodHours: number;
    semiMajorAxisAu: number;
    axialTiltDeg: number;
    eccentricity: number;
    meanTemperatureC: number;
    meanWetness: number;
    oceanPercentage: number;
    landPercentage: number;
    icePercentage: number;
    riverCount: number;
    lakeCellCount: number;
    randomWorldArchetype?: string;
    topologyCellCount: number;
    elevationMin: number;
    elevationMax: number;
    elevationMean: number;
    elevationStdDev: number;
    elevationRoughness: number;
    lowBasinShare: number;
    highReliefShare: number;
    volcanismMean: number;
    activeVolcanismShare: number;
    impactFrequency: number;
    plateCount: number;
    continentalPlateShare: number;
    largestPlateShare: number;
    smallestPlateShare: number;
    plateSizeCoefficientOfVariation: number;
    plateBoundaryCellShare: number;
    meanPlateSpeed: number;
    plateSpeedStdDev: number;
    convergentBoundaryShare: number;
    divergentBoundaryShare: number;
    transformBoundaryShare: number;
    subductionBoundaryShare: number;
    collisionUpliftBoundaryShare: number;
    faultZoneBoundaryShare: number;
    boundaryVolcanismRatio: number;
    tectonicActivityIndex: number;
    movementScore: number;
    boundaryDensityScore: number;
    collisionEnergyScore: number;
    volcanismScore: number;
    cratonCount: number;
    cratonPlateShare: number;
    meanCratonAgeGy: number;
    meanCratonStability: number;
    meanCratonLithosphereThickness: number;
    meanCratonRiftSusceptibility: number;
    oldestCratonAgeGy: number;
    cratonExposureShare: number;
    cratonSubmergedShare: number;
    exposedCratonCellCount: number;
    submergedCratonCellCount: number;
    biomePercentages: Record<string, number>;
};
export type PresetTestResult = {
    testCase: PresetTestCase;
    fingerprint?: WorldFingerprint;
    status: PresetTestStatus;
    findings: string[];
    elapsedMs: number;
    error?: string;
};
export type PresetValidationReport = {
    reportVersion: 2;
    generatedAt: string;
    appVersion: string;
    mode: PresetTestMode;
    resolution: {
        width: 512;
        height: 256;
    };
    topologyResolution: 64;
    seeds: string[];
    totalCases: number;
    results: PresetTestResult[];
    summary: {
        pass: number;
        warning: number;
        fail: number;
        error: number;
    };
    aggregates?: Record<string, number | string>;
    aggregateFindings?: string[];
};
export declare const validationWorldPresets: Record<string, {
    ranges: ParameterRanges;
    tolerance?: number;
}>;
export declare const referenceSeeds: string[];
export declare const deepReferenceSeeds: string[];
export declare function buildTestCases(mode: PresetTestMode): PresetTestCase[];
export declare function configForTestCase(base: GenerationConfig, testCase: PresetTestCase): GenerationConfig;
export declare function fingerprintProject(project: WorldProject): WorldFingerprint;
