import React, { type ReactNode } from 'react';
import type { CoastlineTreatment, MapMode, RenderMode } from '@world-forge/renderer';
import './workspaceToolbar.css';
export type WorkspaceViewMode = 'map' | 'globe';
export type WorkspaceGlobeDebugMode = 'final' | 'albedo' | 'lit' | 'water-mask' | 'sea-level' | 'coast-mask' | 'ocean-shell' | 'neutral-mesh' | 'topology-face' | 'uv-grid' | 'shade' | 'gyres';
export type WorldWorkspaceProps = {
    projectName?: string;
    isGenerating: boolean;
    generationStage: string;
    generationProgress: number;
    generationNodeProgress: Array<{
        nodeId: string;
        label: string;
        progress: number;
        status: 'waiting' | 'running' | 'complete' | 'failed';
        elapsedMs?: number;
    }>;
    viewMode: WorkspaceViewMode;
    showRivers: boolean;
    showPlates: boolean;
    showHexes: boolean;
    hexOverlayLabel?: string;
    diagnosticMode: boolean;
    showGlobeShells: boolean;
    renderMode: RenderMode;
    mapMode: MapMode;
    coastlineTreatment: CoastlineTreatment;
    globeDebugMode: WorkspaceGlobeDebugMode;
    viewZoom: number;
    onViewZoomChange: (zoom: number) => void;
    exportActions: ReactNode;
    developerActions?: ReactNode;
    developerMode?: boolean;
    mapContent: ReactNode;
    legend?: ReactNode;
    onViewModeChange: (mode: WorkspaceViewMode) => void;
    onShowRiversChange: (visible: boolean) => void;
    onShowPlatesChange: (visible: boolean) => void;
    onShowHexesChange: (visible: boolean) => void;
    onToggleDiagnostics: () => void;
    onToggleGlobeShells: () => void;
    onRenderModeChange: (mode: RenderMode) => void;
    onMapModeChange: (mode: MapMode) => void;
    onCoastlineTreatmentChange: (treatment: CoastlineTreatment) => void;
    onGlobeDebugModeChange: (mode: WorkspaceGlobeDebugMode) => void;
};
export declare function WorldWorkspace({ projectName, isGenerating, generationStage, generationProgress, generationNodeProgress, viewMode, showRivers, showPlates, showHexes, hexOverlayLabel, diagnosticMode, showGlobeShells, renderMode, mapMode, coastlineTreatment, globeDebugMode, viewZoom, onViewZoomChange, exportActions, developerActions, developerMode, mapContent, legend, onViewModeChange, onShowRiversChange, onShowPlatesChange, onShowHexesChange, onToggleDiagnostics, onToggleGlobeShells, onRenderModeChange, onMapModeChange, onCoastlineTreatmentChange, onGlobeDebugModeChange }: WorldWorkspaceProps): React.JSX.Element;
